openapi: 3.0.0
info:
  title: Otopark-API
  version: 1.0.0
servers:
  - url: https://otopark-api.herokuapp.com/api/v1
  - url: http://{{url}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
paths:
  /auth/register:
    post:
      tags:
        - default
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: susan
                email: susan@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - default
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: susan@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /slot:
    get:
      tags:
        - default
      summary: Get Slots
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create Slot
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties: {}
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /slot/6370eb86620378229cfaef6c:
    patch:
      tags:
        - default
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                parkingSlot: P-1
                isFull: false
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /slot/6370ebdb620378229cfaeff6:
    delete:
      tags:
        - default
      summary: Delete Slot
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}